export const SET_BUDGET = 'SET_BUDGET';
export const SET_MONTH = 'SET_MONTH';
export const SET_EXPENSE = 'SET_EXPENSE';
export const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
export const SET_CURRENT_BUDGET = 'SET_CURRENT_BUDGET';
export const CLEAR_CURRENT_BUDGET = 'CLEAR_CURRENT_BUDGET';
export const UPDATE_CURRENT_BUDGET = 'UPDATE_CURRENT_BUDGET';
